Update developer_guide.md
1、examples/pytorch/mnist/elastic_debug_job.yaml chang to examples/pytorch/mnist/elastic_job.yaml;
elastic_debug_job.yaml not exist！
2、go at least 1.18 or later

```
$ make deploy IMG=easydl/elasticjob-controller:master
/root/dlrover-0.3.1/dlrover/go/operator/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
Error: err: exit status 1: stderr: go: updates to go.mod needed; to update it:
        go mod tidy
$ go mod tidy
go mod tidy: go.mod file indicates go 1.18, but maximum supported version is 1.17
```
so go at least 1.18 ; like go 1.21.